swagger: "2.0"
info:
  title: API de Gestão de Clínicas
  description: API para gerenciamento de clínica.
  version: "1.0.0"

host: localhost:5000
basePath: /
schemes:
  - http

tags:
  - name: Usuários
    description: Endpoints relacionados a usuários

paths:
  /api/v1/usuarios/login:
    post:
      tags:
        - Usuários
      summary: Login de usuário
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: Credenciais do usuário
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
                example: example@gmail.com
              senha:
                type: string
                example: senha123
      responses:
        200:
          description: Logado com sucesso
          schema:
            type: object
            properties:
              token:
                type: string
              msg:
                type: string
                example: Logado com sucesso
        400:
          description: E-mail e senha são campos obrigatórios
        404:
          description: E-mail ou senha incorretas
        500:
          description: Erro interno

  /api/v1/usuarios/{email}:
    get:
      tags:
        - Usuários
      summary: Obter informações de um usuário (protegido) (admin)
      parameters:
        - name: email
          in: path
          required: true
          type: string
        - name: Authorization
          in: header
          required: true
          type: string
      responses:
        200:
          description: Usuário encontrado
          examples:
            application/json:
              usuario:
                    email: admin@consultorio.com
                    id: 1
                    nome: admin
                    senha: admin69
                    tipo: admin
        401:
          description: Não autorizado
        403:
          description: Acesso negado
        404:
          description: Usuário não encontrado
        500:
          description: Erro interno

  /api/v1/usuarios:
    get:
      tags:
        - Usuários
      summary: Listar usuários de forma paginada (protegido) (admin)
      parameters:
        - name: pagina
          in: query
          type: integer
          default: 1
        - name: itensPorPagina
          in: query
          type: integer
          default: 2
        - name: Authorization
          in: header
          required: true
          type: string
      responses:
        200:
          description: Lista de usuários retornada
          examples:
            application/json:
              itensPorPagina: 2
              pagina: 1
              totalPaginas: 1
              usuariosTotais: 2
              usuarios:
                - email: admin@consultorio.com
                  id: 1
                  nome: admin
                  senha: admin69
                  tipo: admin
                - email: exampledefault@gmail.com
                  id: 2
                  nome: default
                  senha: 123456
                  tipo: default
        401:
          description: Não autorizado
        403:
          description: Acesso negado
        404:
          description: Index indisponível
        500:
          description: Erro interno

  /api/v1/usuarios/adicionar:
    post:
      tags:
        - Usuários
      summary: Adicionar um novo usuário (protegido) (admin)
      consumes:
        - application/json
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              nome:
                type: string
              tipo:
                type: string
                enum: [admin, default]
      responses:
        200:
          description: Usuário criado com sucesso
        400:
          description: Campos obrigatórios ausentes ou tipo inválido
        401:
          description: Não autorizado
        403:
          description: Acesso negado
        409:
          description: Email já cadastrado
        500:
          description: Erro interno

  /api/v1/usuarios/editar:
    put:
      tags:
        - Usuários
      summary: Editar informações próprias do usuário (protegido)
      consumes: 
        - application/json
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              nome:
                type: string
      responses:
        200:
          description: Dados do usuário atualizados
        400:
          description: Campos obrigatórios não informados
        401:
          description: Não autorizado
        409:
          description: Email já cadastrado
        500:
          description: Erro interno

  /api/v1/usuarios/alterarSenha:
    put:
      tags:
        - Usuários
      summary: Alterar a própria senha (protegido)
      consumes:
        - application/json
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              senha:
                type: string
              novaSenha:
                type: string
      responses:
        200:
          description: Senha alterada com sucesso
        400:
          description: Campos obrigatórios não informados
        401:
          description: Não autorizado
        401:
          description: Senha incorreta
        500:
          description: Erro interno

  /api/v1/usuarios/resetarSenha:
    put:
      tags:
        - Usuários
      summary: Resetar senha de um usuário (protegido) (admin)
      consumes:
        - application/json
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
      responses:
        200:
          description: Senha resetada com sucesso
        400:
          description: Campos obrigatórios não informados
        401:
          description: Não autorizado
        403:
          description: Acesso negado
        404:
          description: Usuário não encontrado
        500:
          description: Erro interno

  /api/v1/usuarios/deletar:
    delete:
      tags:
        - Usuários
      summary: Deletar um usuário (protegido) (admin)
      consumes:
        - application/json
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
      responses:
        200:
          description: Usuário deletado com sucesso
        400:
          description: Campos obrigatórios não informados
        401:
          description: Não autorizado
        403:
          description: Acesso negado
        404:
          description: Usuário não encontrado
        409:
          description: Não é possível deletar usuário com atendimentos vinculados
        500:
          description: Erro interno
